backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images/uploads
public_folder: /images/uploads
site_url: https://hasanavi.me
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Page Title", name: "page_title", widget: "string" }
          - { label: "Page SubTitle", name: "page_subtitle", widget: "string" }
          - {
              label: "Page Description",
              name: "page_description",
              widget: "text",
            }
          - {
              label: "Projects Title",
              name: "projects_title",
              widget: "string",
            }
          - {
              label: "Projects Image",
              name: "projects_image",
              widget: "image",
              allow_multiple: false,
              choose_url: false,
            }
